CANDIDATOS = {
    "Selecciona un candidato...": None,
    "Keiko Fujimori — Fuerza Popular": {"nombre": "Keiko Fujimori", "partido": "Fuerza Popular"},
    "Rafael López Aliaga — Renovación Popular": {"nombre": "Rafael López Aliaga", "partido": "Renovación Popular"},
    "César Acuña — Alianza para el Progreso": {"nombre": "César Acuña", "partido": "Alianza para el Progreso"},
    "George Forsyth — Somos Perú": {"nombre": "George Forsyth", "partido": "Somos Perú"},
    "José Williams — Avanza País": {"nombre": "José Williams", "partido": "Avanza País"},
    "Alfonso López Chau — Ahora Nación": {"nombre": "Alfonso López Chau", "partido": "Ahora Nación"},
    "Alfredo Barnechea — Acción Popular": {"nombre": "Alfredo Barnechea", "partido": "Acción Popular"},
    "Yonhy Lescano — Cooperación Popular": {"nombre": "Yonhy Lescano", "partido": "Cooperación Popular"},
    "Roberto Sánchez — Juntos por el Perú": {"nombre": "Roberto Sánchez", "partido": "Juntos por el Perú"},
    "Mesías Guevara — Partido Morado": {"nombre": "Mesías Guevara", "partido": "Partido Morado"},
    "Marisol Pérez Tello — Primero la Gente": {"nombre": "Marisol Pérez Tello", "partido": "Primero la Gente"},
    "Fernando Olivera — Frente de la Esperanza 2021": {"nombre": "Fernando Olivera", "partido": "Frente de la Esperanza 2021"},
    "Vladimir Cerrón — Perú Libre": {"nombre": "Vladimir Cerrón", "partido": "Perú Libre"},
    "José Luna Gálvez — Podemos Perú": {"nombre": "José Luna Gálvez", "partido": "Podemos Perú"},
    "Mario Vizcarra — Perú Primero": {"nombre": "Mario Vizcarra", "partido": "Perú Primero"},
    "Álvaro Paz de la Barra — Fe en el Perú": {"nombre": "Álvaro Paz de la Barra", "partido": "Fe en el Perú"},
    "Fiorella Molinelli — Fuerza y Libertad": {"nombre": "Fiorella Molinelli", "partido": "Fuerza y Libertad"},
    "Jorge Nieto — Partido del Buen Gobierno": {"nombre": "Jorge Nieto", "partido": "Partido del Buen Gobierno"},
    "Rosario Fernández — Un Camino Diferente": {"nombre": "Rosario Fernández", "partido": "Un Camino Diferente"},
    "Walter Chirinos — PRIN": {"nombre": "Walter Chirinos", "partido": "PRIN"},
    "Ricardo Belmont — Obras": {"nombre": "Ricardo Belmont", "partido": "Obras"},
    "Carlos Álvarez — País Para Todos": {"nombre": "Carlos Álvarez", "partido": "País Para Todos"},
    "Paul Jaimes — Progresemos": {"nombre": "Paul Jaimes", "partido": "Progresemos"},
    "Carlos Espá — Sí Creo": {"nombre": "Carlos Espá", "partido": "Sí Creo"},
    "Ronald Atencio — Venceremos": {"nombre": "Ronald Atencio", "partido": "Venceremos"},
    "Antonio Ortiz — Salvemos al Perú": {"nombre": "Antonio Ortiz", "partido": "Salvemos al Perú"},
    "Herbert Caller — Partido Patriótico del Perú": {"nombre": "Herbert Caller", "partido": "Partido Patriótico del Perú"},
    "Charlie Carrasco — Partido Demócrata Unido": {"nombre": "Charlie Carrasco", "partido": "Partido Demócrata Unido"},
    "Armando Massé — Partido Democrático Federal": {"nombre": "Armando Massé", "partido": "Partido Democrático Federal"},
    "Wolfgang Grozo — Integridad Democrática": {"nombre": "Wolfgang Grozo", "partido": "Integridad Democrática"},
    "Carlos Jaico — Perú Moderno": {"nombre": "Carlos Jaico", "partido": "Perú Moderno"},
    "Rafael Belaunde — Libertad Popular": {"nombre": "Rafael Belaunde", "partido": "Libertad Popular"},
    "Roberto Chiabra — Unidad Nacional": {"nombre": "Roberto Chiabra", "partido": "Unidad Nacional"},
    "Napoleón Becerra — Trabajadores y Emprendedores": {"nombre": "Napoleón Becerra", "partido": "Trabajadores y Emprendedores"},
    "Alex Gonzales — Partido Demócrata Verde": {"nombre": "Alex Gonzales", "partido": "Partido Demócrata Verde"},
    "Francisco Diez Canseco — Perú Acción": {"nombre": "Francisco Diez Canseco", "partido": "Perú Acción"},
}
